name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Set up Firebase Environment Variables
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PERMISSIONS: ${{ secrets.FIREBASE_PERMISSIONS }}
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_AUTH_URI: ${{ secrets.FB_AUTH_URI }}
          FB_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FB_AUTH_PROVIDER_X509_CERT_URL }}
          FB_PRIVATE_KEY_ID: ${{ secrets.FB_PRIVATE_KEY_ID }}
          FB_PRIVATE_KEY: ${{ secrets.FB_PRIVATE_KEY }}
          FB_TOKEN_URI: ${{ secrets.FB_TOKEN_URI }}
          FB_CLIENT_EMAIL: ${{ secrets.FB_CLIENT_EMAIL }}
          FB_CLIENT_X509_CERT_URL: ${{ secrets.FB_CLIENT_X509_CERT_URL }}
          FB_CLIENT_ID: ${{ secrets.FB_CLIENT_ID }}
          FB_DATABASE_URL: ${{ secrets.FB_DATABASE_URL }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
        run: echo "Firebase environment variables set"

      - name: Install Dependencies
        run: |
          cd functions
          npm install
          npm install -g firebase-tools

      - name: create config json
        uses: jsdaniell/create-json@1.1.2
        id: create-config-json
        with:
          name: 'permissions.json'
          json: '{"type": "${FB_PROJECT_ID}","auth_uri": "${FB_AUTH_URI}","auth_provider_x509_cert_url": "${FB_AUTH_PROVIDER_X509_CERT_URL}","private_key_id": "${FB_PRIVATE_KEY_ID}","project_id": "${FB_PROJECT_ID}","private_key": "${FB_PRIVATE_KEY/\n/\n}","token_uri": "${FB_TOKEN_URI}", "client_email": "${FB_CLIENT_EMAIL}","client_x509_cert_url": "${FB_CLIENT_X509_CERT_URL}","client_id": "${FB_CLIENT_ID}"}'
          dir: 'functions/src/config/database/'

      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
