name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Set up Firebase Environment Variables
        env:
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_CLIENT_EMAIL: ${{ secrets.FB_CLIENT_EMAIL }}
          FB_PRIVATE_KEY: ${{ secrets.FB_PRIVATE_KEY }}
          FB_DATABASE_URL: ${{ secrets.FB_DATABASE_URL }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: echo "Firebase environment variables set"

      - name: Install Dependencies
        run: |
          cd backend
          npm install
          npm install -g firebase-tools
      
      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
